apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: asset-injector-base
  annotations:
    config.kubernetes.io/local-config: "true"

resources:
- deployment.yaml
- service.yaml
- configmap.yaml
- pvc.yaml
- networkpolicy.yaml

commonLabels:
  app: asset-injector
  component: microservice

namePrefix: ""
nameSuffix: ""

images:
- name: ghcr.io/asset-injector/asset-injector
  newTag: latest

configMapGenerator: []
secretGenerator: []

replicas:
- name: asset-injector
  count: 2